#!/bin/bash
#shraddha shinde


# Check if hostname argument is provided
if [ -z "$1" ]; then
    echo "Please provide a username:hostname."
    echo "Usage: $0 username:hostname "
    exit 1
fi

# get the reequired remote machine specs 
get_cpu_mem_disk_specs() {
    echo "Retrieving system specifications for `hostname`"
    echo "**********************************"
    echo "CPU Information:"
    #top | head -5 
    lscpu | grep 'CPU(s)'
    echo "**********************************"
    echo "Memory Information:"
    free -h
    echo "**********************************"
    echo "Disk Information:"
    df -h
}


if [[ "$(uname)" == "Linux" ]]; then

#add the remote machine details for which specs are required
ssh $1 "$(typeset -f); get_cpu_mem_disk_specs"
else
    echo "Unsupported OS."
fi
